---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven   
    
inputs:
  - name: source-repo
  - name: version

outputs:
  - name: build-output
  - name: source-repo-update-tag

caches:
  - path: .m2/repository
  
run:
  path: /bin/bash
  args:
    - source-repo/ci/tasks/package.sh