---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: concourse/buildroot
    tag: git   
    
inputs:
  - name: minio-s3-bucket-pom
  
outputs:
  - name: source-repo-update-pom

run:
  path: /bin/bash
  args:
    - source-repo/ci/tasks/pom-push.sh