---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: alpine   
    
inputs:
  - name: source-repo

run:
  path: /bin/bash
  args:
    - source-repo/ci/tasks/smoke-test.sh