---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven   
    
inputs:
  - name: source-repo

outputs:
  - name: build-output

caches:
  - path: .m2/repository
  
run:
  path: /bin/bash
  args:
    - source-repo/ci/tasks/unit-test.sh